on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          cache: 'gradle'
      - name: Run the tests
        run: ./gradlew test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          cache: 'gradle'
      - name: Run the linter
        run: ./gradlew lintKotlin